Algoritmo PRODUCTO_DE_SUMAS
	DEFINIR N1,N2 Como Entero
	N1=0;N2=0;C=0;ACUM=0
	ESCRIBIR "ESCRIBA UN NUMERO"
	LEER N1
	ESCRIBIR "ESCRIBA UN NUMERO"
	LEER N2
	MIENTRAS C<N1 HACER 
		C=C+1
		ACUM=ACUM+N2
	
	
		
	FinMientras
	ESCRIBIR "EL PRODUCTO DE LA SUMA ES IGUAL ",ACUM
FinAlgoritmo
