Algoritmo PRODUCTO_DE_DOS_NUMEROS
	DEFINIR NUM1,NUM2,PRODUCTO COMO REAL
	NUM1=0;NUM2=0;PRODUCTO=0
	ESCRIBIR"ESCRIBA UN NUMERO"
	LEER NUM1
	Escribir "ESCRIBA OTRO NUMERO"
	LEER NUM2
	PRODUCTO=NUM1*NUM2
	ESCRIBIR "EL PRODUCTO DE DOS NUMEROS ES ",PRODUCTO
	
	
FinAlgoritmo
