Algoritmo MAYOR_DE_DOS_NUMEROS
	DEFINIR N1,N2 COMO REAL
	N1=0;N2=0
	ESCRIBIR"DE UN PRIMER NUMERO"
	LEER N1
	ESCRIBIR"DE UN SEGUNDO NUMERO"
	LEER N2
	Si N1>N2 Entonces
		ESCRIBIR "EL PRIMER NUMERO ES MAYOR "
	SiNo
		ESCRIBIR "EL SEGUNDO NUMERO ES MAYOR "
	Fin Si
	
	
	
FinAlgoritmo
