Algoritmo MAYOR_DE_3_NUMEROS
	DEFINIR N1,N2,N3 Como Real
	N1=0;N2=0;N3=0
	ESCRIBIR "DE UN PRIMER NUMERO"
	LEER N1
	ESCRIBIR "DE UN SEGUNDO NUMERO"
	LEER N2
	ESCRIBIR "DE UN TERCER NUMERO"
	LEER N3
	SI N1>N2 Y N1>N3 Entonces
		ESCRIBIR "EL  NUMERO MAYOR ES ",N1
	SINO 
		SI N2>N1 Y N2>N3 ENTONCES 
			ESCRIBIR "EL NUMERO MAYOR ES ",N2
		SINO 
			ESCRIBIR"EL NUMERO MAYOR ES  ",N3
		FinSi
	FinSi
	
		
	
FinAlgoritmo
